### ISSUE TITLE
Makefile shouldn't hardcode location of CC

### ISSUE THREAD

**Issue by snej** [AlexDenisov/bitcode_retriever#2]
`make` failed for me, because the first line of the Makefile defines the `CC` variable to point to a specific location of the Clang command inside an Xcode-beta.app. I commented out that line, and then the build worked.

If you're having to specify where the compiler is, it sounds like you haven't run the `xcode-select` tool to point your dev tools to your copy of Xcode. Once you do that, simply invoking `clang` or `cc` will work fine.

**Comment by AlexDenisov** [comment]
Could you open pull request with fix and update for 'documentation'?

**Comment by snej** [comment]
Sorry, I just downloaded a zip instead of checking it out from git, and I've already deleted it as it doesn't meet my needs (it doesn't appear to work on static libraries: the tool just locked up forever when I tried to run it, without generating any files.)

It would be a lot easier for you to delete that line and commit, than for me to check out the repo, delete the line, submit a PR, etc.

**Comment by AlexDenisov** [comment]
> It would be a lot easier for you to delete that line and commit, than for me to check out the repo, delete the line, submit a PR, etc.

Sure, I will do it.

> it doesn't meet my needs (it doesn't appear to work on static libraries

Please, take my apologies for this confusion. Initially the tool wasn't intended to be a 'production-ready', it was just a proof of concept, to confirm my observations.

I also discovered that it doesn't work with static libraries because of slightly different format, I even opened an issue (#1), but didn't get time to fix that.

I can ping you whenever it's done, If you still interested.

Thank you for your feedback, @snej, I really appreciate it.

**Comment by snej** [comment]
Oh, no problem! I understood that the tool was just a quick hack to meet your own needs. :)

I just heard from someone that I can use `otool -l | grep __LLVM` to search for the presence of bitcode in a library, which is all I need for my purposes.
